In [16]:
import pandas as pd

df_categorias = pd.read_parquet("categorias.parquet")
df_libros = pd.read_parquet("libros.parquet")

df_categorias.head()

,categoria,url_categoria,cantidad_libros,fecha_extraccion,extraido_por
0,Travel,https://books.toscrape.com/catalogue/category/...,11,2026-08-15T13:49:07,Pablo y Pedro
1,Mystery,https://books.toscrape.com/catalogue/category/...,32,2026-08-15T13:49:22,Pablo y Pedro
2,Historical Fiction,https://books.toscrape.com/catalogue/category/...,26,2026-08-15T13:49:36,Pablo y Pedro
3,Sequential Art,https://books.toscrape.com/catalogue/category/...,75,2026-08-15T13:50:17,Pablo y Pedro
4,Classics,https://books.toscrape.com/catalogue/category/...,19,2026-08-15T13:50:29,Pablo y Pedro

In [17]:
df_libros.head()

,upc,titulo,categoria,descripcion,tipo_producto,precio_sin_impuesto,precio_con_impuesto,impuesto,moneda,disponibilidad,cantidad_stock,calificacion,cantidad_resenas,url_libro,url_imagen,fecha_extraccion,extraido_por
0,a22124811bfa8350,It's Only the Himalayas,Travel,"“Wherever you go, whatever you do, just . . . ...",Books,45.17,45.17,0.0,GBP,In stock (19 available),19,2,0,https://books.toscrape.com/catalogue/its-only-...,https://books.toscrape.com/media/cache/6d/41/6...,2026-08-15T13:49:03,Pablo y Pedro
1,ce60436f52c5ee68,Full Moon over Noah’s Ark: An Odyssey to Mount...,Travel,Acclaimed travel writer Rick Antonson sets his...,Books,49.43,49.43,0.0,GBP,In stock (15 available),15,4,0,https://books.toscrape.com/catalogue/full-moon...,https://books.toscrape.com/media/cache/fe/8a/f...,2026-08-15T13:49:04,Pablo y Pedro
2,f9705c362f070608,See America: A Celebration of Our National Par...,Travel,To coincide with the 2016 centennial anniversa...,Books,48.87,48.87,0.0,GBP,In stock (14 available),14,3,0,https://books.toscrape.com/catalogue/see-ameri...,https://books.toscrape.com/media/cache/c7/1a/c...,2026-08-15T13:49:04,Pablo y Pedro
3,1809259a5a5f1d8d,Vagabonding: An Uncommon Guide to the Art of L...,Travel,With a new foreword by Tim Ferriss •There’s no...,Books,36.94,36.94,0.0,GBP,In stock (8 available),8,2,0,https://books.toscrape.com/catalogue/vagabondi...,https://books.toscrape.com/media/cache/ca/30/c...,2026-08-15T13:49:05,Pablo y Pedro
4,a94350ee74deaa07,Under the Tuscan Sun,Travel,A CLASSIC FROM THE BESTSELLING AUTHOR OF UNDER...,Books,37.33,37.33,0.0,GBP,In stock (7 available),7,3,0,https://books.toscrape.com/catalogue/under-the...,https://books.toscrape.com/media/cache/45/21/4...,2026-08-15T13:49:05,Pablo y Pedro

## 1. ¿Cuántas categorías de libros existen?

In [18]:
num_categorias = df_categorias["categoria"].nunique()
print(f"Número de categorías: {num_categorias}")

Número de categorías: 50

## 2. ¿Cuántos libros hay en cada categoría?

In [19]:
libros_por_categoria = df_libros.groupby("categoria").size().reset_index(name="cantidad_libros")
libros_por_categoria = libros_por_categoria.sort_values("cantidad_libros", ascending=False).reset_index(drop=True)
libros_por_categoria

             categoria  cantidad_libros
0              Default              152
1           Nonfiction              110
2       Sequential Art               75
3        Add a comment               67
4              Fiction               65
5          Young Adult               54
6              Fantasy               48
7              Romance               35
8              Mystery               32
9       Food and Drink               30
10           Childrens               29
11  Historical Fiction               26
12              Poetry               19
13            Classics               19
14             History               18
15      Womens Fiction               17
16              Horror               17
17     Science Fiction               16
18             Science               14
19               Music               13
20            Business               12
21          Philosophy               11
22            Thriller               11
23              Travel               11
24               Humor               10
25       Autobiography                9
26                 Art                8
27            Religion                7
28          Psychology                7
29   Christian Fiction                6
30        Spirituality                6
31           New Adult                6
32    Sports and Games                5
33           Biography                5
34           Self Help                5
35              Health                4
36        Contemporary                3
37            Politics                3
38           Christian                3
39          Historical                2
40            Academic                1
41       Adult Fiction                1
42             Erotica                1
43            Cultural                1
44               Crime                1
45              Novels                1
46          Paranormal                1
47           Parenting                1
48            Suspense                1
49       Short Stories                1

## 3. ¿Cuál es el libro más caro?

In [20]:
precio_maximo = df_libros["precio_con_impuesto"].max()
libros_mas_caros = df_libros[df_libros["precio_con_impuesto"] == precio_maximo]
print(f"Precio máximo (con impuesto): {precio_maximo}")
libros_mas_caros[["upc", "titulo", "categoria", "precio_con_impuesto"]]

Precio máximo (con impuesto): 59.99

,upc,titulo,categoria,precio_con_impuesto
191,9cc207168a03470d,The Perfect Play (Play by Play #1),Romance,59.99

## 4. ¿Hay algún libro que aparezca en más de una categoría?

In [21]:
conteo_upc = df_libros.groupby("upc")["categoria"].nunique()
upcs_en_varias_categorias = conteo_upc[conteo_upc > 1]

if upcs_en_varias_categorias.empty:
    print("No hay ningún libro que aparezca en más de una categoría.")
else:
    print(f"Hay {len(upcs_en_varias_categorias)} libros que aparecen en más de una categoría:")
    display(df_libros[df_libros["upc"].isin(upcs_en_varias_categorias.index)][["upc", "titulo", "categoria"]].sort_values("upc"))

No hay ningún libro que aparezca en más de una categoría.

## 5. ¿Cuál es el libro más barato de cada categoría?

In [22]:
precio_min_por_categoria = df_libros.groupby("categoria")["precio_con_impuesto"].transform("min")
libros_mas_baratos = df_libros[df_libros["precio_con_impuesto"] == precio_min_por_categoria]
libros_mas_baratos = libros_mas_baratos.sort_values(["categoria", "titulo"]).reset_index(drop=True)
libros_mas_baratos[["categoria", "titulo", "precio_con_impuesto"]]

,categoria,titulo,precio_con_impuesto
0,Academic,Logan Kade (Fallen Crest High #5.5),13.12
1,Add a comment,The Tipping Point: How Little Things Can Make ...,10.02
2,Adult Fiction,Fifty Shades Freed (Fifty Shades #3),15.36
3,Art,History of Beauty,10.29
4,Autobiography,The Argonauts,10.93
5,Biography,Louisa: The Extraordinary Life of Mrs. Adams,16.85
6,Business,The Third Wave: An Entrepreneur’s Vision of th...,12.61
7,Childrens,Counting Thyme,10.62
8,Christian,Blue Like Jazz: Nonreligious Thoughts on Chris...,25.77
9,Christian Fiction,Counted With the Stars (Out from Egypt #1),17.97
10,Classics,The Hound of the Baskervilles (Sherlock Holmes...,14.82
11,Contemporary,We Are All Completely Beside Ourselves,24.04
12,Crime,The Long Shadow of Small Ghosts: Murder and Me...,10.97
13,Cultural,Amid the Chaos,36.58
14,Default,Greek Mythic History,10.23
15,Erotica,Dark Notes,19.19
16,Fantasy,Every Heart a Doorway (Every Heart A Doorway #1),12.16
17,Fiction,I Am Pilgrim (Pilgrim #1),10.60
18,Food and Drink,The Power Greens Cookbook: 140 Delicious Super...,11.05
19,Health,The Bulletproof Diet: Lose up to a Pound a Day...,49.05
20,Historical,The Girl You Left Behind (The Girl You Left Be...,15.79
21,Historical Fiction,The Constant Princess (The Tudor Court #1),16.62
22,History,Brilliant Beacons: A History of the American L...,11.45
23,Horror,Pet Sematary,10.56
24,Humor,Old School (Diary of a Wimpy Kid #10),11.83
25,Music,Orchestra of Exiles: The Story of Bronislaw Hu...,12.36
26,Mystery,Tastes Like Fear (DI Marnie Rome #3),10.69
27,New Adult,The Hook Up (Game On #1),36.29
28,Nonfiction,"The Sleep Revolution: Transforming Your Life, ...",11.68
29,Novels,Suzie Snowflake: One beautiful flake (a self-e...,54.81
30,Paranormal,"Vampire Knight, Vol. 1 (Vampire Knight #1)",15.40
31,Parenting,Catastrophic Happiness: Finding Joy in Childho...,37.35
32,Philosophy,Sophie's World,15.94
33,Poetry,Poems That Make Grown Women Cry,14.19
34,Politics,Libertarianism for Beginners,51.33
35,Psychology,The Lucifer Effect: Understanding How Good Peo...,10.40
36,Religion,You Are What You Love: The Spiritual Power of ...,21.87
37,Romance,Reservations for Two,11.10
38,Science,The Origin of Species,10.01
39,Science Fiction,The Project,10.65
40,Self Help,You Are a Badass: How to Stop Doubting Your Gr...,12.08
41,Sequential Art,Patience,10.16
42,Short Stories,The Grownup,35.88
43,Spirituality,The Four Agreements: A Practical Guide to Pers...,17.66
44,Sports and Games,Sugar Rush (Offensive Line #2),24.42
45,Suspense,Silence in the Dark (Logan Point #4),58.33
46,Thriller,In Her Wake,12.84
47,Travel,The Road to Little Dribbling: Adventures of an...,23.21
48,Womens Fiction,Some Women,13.73
49,Young Adult,An Abundance of Katherines,10.00

## 6. Diferencia entre el precio de cada libro y el precio promedio de su categoría

`diferencia = precio del libro - precio promedio de su categoría`

- Positivo -> el libro es más caro que el promedio de su categoría.
- Negativo -> el libro es más barato que el promedio de su categoría.
- Cero -> cuesta lo mismo que el promedio.

In [23]:
promedio_por_categoria = df_libros.groupby("categoria")["precio_con_impuesto"].transform("mean")
df_libros["diferencia"] = df_libros["precio_con_impuesto"] - promedio_por_categoria

df_libros[["upc", "titulo", "categoria", "precio_con_impuesto", "diferencia"]].sort_values("diferencia", ascending=False).head(10)

,upc,titulo,categoria,precio_con_impuesto,diferencia
925,6478ccb4416e6a5d,The Barefoot Contessa Cookbook,Food and Drink,59.92,28.505333
964,9c4d061c1e2fe6bf,The Bone Hunters (Lexy Vaughan & Steven Macaul...,Thriller,59.71,28.276364
25,49b24c6a41b82bd2,Boar Island (Anna Pigeon #19),Mystery,59.48,27.760937
191,9cc207168a03470d,The Perfect Play (Play by Play #1),Romance,59.99,26.056286
38,b0913e67d38d5ed5,The No. 1 Ladies' Detective Agency (No. 1 Ladi...,Mystery,57.70,25.980938
845,396385e3de5d18c3,Civilization and Its Discontents,Psychology,59.95,25.731429
368,54fc03f1e1d355db,The Diary of a Young Girl,Nonfiction,59.90,25.639818
294,37c0cb19713d8dda,The White Cat and the Monk: A Retelling of the...,Childrens,58.08,25.441724
392,60376aa71be66083,The Man Who Mistook His Wife for a Hat and Oth...,Nonfiction,59.45,25.189818
203,6e712ea24e77bd96,Listen to Me (Fusion #1),Romance,58.99,25.056286

## 7. Libro con mayor ingreso potencial dentro de cada categoría

`ingreso potencial = precio_con_impuesto × cantidad_stock`

In [24]:
df_libros["ingreso_potencial"] = df_libros["precio_con_impuesto"] * df_libros["cantidad_stock"]

ingreso_max_por_categoria = df_libros.groupby("categoria")["ingreso_potencial"].transform("max")
libros_mayor_ingreso = df_libros[df_libros["ingreso_potencial"] == ingreso_max_por_categoria]
libros_mayor_ingreso = libros_mayor_ingreso.sort_values(["categoria", "titulo"]).reset_index(drop=True)
libros_mayor_ingreso[["categoria", "titulo", "precio_con_impuesto", "cantidad_stock", "ingreso_potencial"]]

,categoria,titulo,precio_con_impuesto,cantidad_stock,ingreso_potencial
0,Academic,Logan Kade (Fallen Crest High #5.5),13.12,5,65.60
1,Add a comment,Judo: Seven Steps to Black Belt (an Introducto...,53.90,16,862.40
2,Adult Fiction,Fifty Shades Freed (Fifty Shades #3),15.36,3,46.08
3,Art,Wall and Piece,44.18,18,795.24
4,Autobiography,Lab Girl,40.85,11,449.35
5,Biography,Benjamin Franklin: An American Life,48.19,7,337.33
6,Business,The Dirty Little Secrets of Getting Your Dream...,33.34,19,633.46
7,Childrens,Birdsong: A Story in Pictures,54.64,19,1038.16
8,Christian,(Un)Qualified: How God Uses Broken People to D...,54.00,16,864.00
9,Christian Fiction,Close to You,49.46,15,741.90
10,Classics,Candide,58.63,4,234.52
11,Contemporary,Someone Like You (The Harrisons #2),52.79,14,739.06
12,Crime,The Long Shadow of Small Ghosts: Murder and Me...,10.97,15,164.55
13,Cultural,Amid the Chaos,36.58,15,548.70
14,Default,Aladdin and His Wonderful Lamp,53.13,19,1009.47
15,Erotica,Dark Notes,19.19,15,287.85
16,Fantasy,Masks and Shadows,56.40,16,902.40
17,Fiction,Soumission,50.10,20,1002.00
18,Food and Drink,The Pioneer Woman Cooks: Dinnertime: Comfort C...,56.41,16,902.56
19,Health,The Bulletproof Diet: Lose up to a Pound a Day...,49.05,16,784.80
20,Historical,All the Light We Cannot See,29.87,14,418.18
21,Historical Fiction,Tipping the Velvet,53.74,20,1074.80
22,History,Sapiens: A Brief History of Humankind,54.23,20,1084.60
23,Horror,Security,39.25,16,628.00
24,Humor,The Long Haul (Diary of a Wimpy Kid #9),44.07,14,616.98
25,Music,Our Band Could Be Your Life: Scenes from the A...,57.25,19,1087.75
26,Mystery,Sharp Objects,47.82,20,956.40
27,New Adult,The Matchmaker's Playbook (Wingmen Inc. #1),55.85,15,837.75
28,Nonfiction,The Electric Pencil: Drawings from Inside Stat...,56.06,16,896.96
29,Novels,Suzie Snowflake: One beautiful flake (a self-e...,54.81,9,493.29
30,Paranormal,"Vampire Knight, Vol. 1 (Vampire Knight #1)",15.40,1,15.40
31,Parenting,Catastrophic Happiness: Finding Joy in Childho...,37.35,3,112.05
32,Philosophy,The Death of Humanity: and the Case for Life,58.11,16,929.76
33,Poetry,A Light in the Attic,51.77,22,1138.94
34,Politics,Libertarianism for Beginners,51.33,19,975.27
35,Psychology,It Didn't Start with You: How Inherited Family...,56.27,11,618.97
36,Religion,Don't Be a Jerk: And Other Practical Advice fr...,37.97,16,607.52
37,Romance,Suddenly in Love (Lake Haven #1),55.99,15,839.85
38,Science,Immunity: How Elie Metchnikoff Changed the Cou...,57.36,16,917.76
39,Science Fiction,Mesaerion: The Best Science Fiction Stories 18...,37.59,19,714.21
40,Self Help,Online Marketing for Busy Authors: A Step-By-S...,46.35,16,741.60
41,Sequential Art,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,19,993.51
42,Short Stories,The Grownup,35.88,8,287.04
43,Spirituality,Chasing Heaven: What Dying Taught Me About Living,37.80,15,567.00
44,Sports and Games,"Friday Night Lights: A Town, a Team, and a Dream",51.22,3,153.66
45,Suspense,Silence in the Dark (Logan Point #4),58.33,8,466.64
46,Thriller,Behind Closed Doors,52.22,18,939.96
47,Travel,It's Only the Himalayas,45.17,19,858.23
48,Womens Fiction,I Had a Nice Time And Other Lies...: How to fi...,57.36,15,860.40
49,Young Adult,Aristotle and Dante Discover the Secrets of th...,58.14,14,813.96